### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by victorperin** [Renegade-Master/zomboid-dedicated-server#1]
I think it's possible to run on startup the admin password using `-adminpassword` option when starting the server. This could enable setting an environment variable and pass it during the first startup.

**Comment by Renegade-Master** [comment]
Oh, really?  Awesome.  I will give this a go.  
It has been one of my main gripes with this process so far.

**Comment by Renegade-Master** [comment]
Yep, looked through the game source (which is very handily distributed alongside the game), and there are indeed some extra parameters that I wasn't aware of.

- `-disablelog=XX`
- `-debuglog=XX`
- `-servername`
- `-adminusername`
- `-adminpassword`
- `-cachedir=XX`
- `-ip=XX`
- `-port`
- `-gui`
- `-nosteam`
- `-statistic`
- `-steamvac`
- `-coop`

I don't know what they all do exactly, but I will be adding as many as I can make sense of in the next release.

Thank you again for bringing this to my attention!

**Comment by Renegade-Master** [comment]
This functionality (and more) has been added as of Release 1.2.0 (see [commit](https://github.com/Renegade-Master/zomboid-dedicated-server/commit/415798b401caa896e89f41dd14e558929eeab86d)).

Please let me know if there are any other improvements that can be made.

Closing this ticket now, if there are problems associated with this, simply re-open the ticket.
