### ISSUE TITLE
Graceful shutdown on SIGTERM/SIGINT

### ISSUE THREAD

**Issue by ramielrowe** [Renegade-Master/zomboid-dedicated-server#12]
**Is your feature request related to a problem? Please describe.**
I'm not sure how graceful the server handles SIGTERM/SIGINT. The way I have been shutting down the server in the past has been to issue a `quit` command on the terminal where I launched the server.

**Describe the solution you'd like**
When `run_server.sh` receives a SIGTERM/SIGINT it outputs `quit\n` to the launched server's `stdin`.

**Describe alternatives you've considered**
It may also be possible to issue `quit` via a RCON CLI to the RCON port, but I haven't tried that yet. This may be easier than trying to manage sending the command over stdin.

**Additional context**
None

**Comment by ramielrowe** [comment]
I may take this on next free weekend I get. But still, looking for feedback on this idea.

**Comment by Renegade-Master** [comment]
Seems like a good idea. It would be easy enough to capture the exit code. It would only be visable from the container logs though. If you are already monitoring those that should not be a problem.

Not sure how my use of `timeout` might affect this yet though.

And RCON can be supported. I just did not initially see it as essential, so I have not enabled it on this image thus far. Again, would be easy to add.

**Comment by Renegade-Master** [comment]
I will look into it a bit more, but from what I can tell:
My use of `timeout` means that `SIGTERM` at least should be sent to the application when the container shuts down. Issuing a `docker stop ...` or `docker-compose down` should send a `SIGTERM` to the application.
