### ISSUE TITLE
env RCONPassword

### ISSUE THREAD

**Issue by axi92** [Renegade-Master/zomboid-dedicated-server#16]
**Is your feature request related to a problem? Please describe.**
-
I came from a different container that stoped working and I had there the ADMIN_PASSWORD and RCON_PASSWORD.
ADMIN_PASSWORD is fine but the RCON_PASSWORD env is missing

**Describe the solution you'd like**
-
To have the env var in the compose file for RCONPassword

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Renegade-Master** [comment]
Hello! Thank you for raising this Fearure Request.

I do not currently support RCON, but it is being implemented by another contributor in #15.
I may start to work on it myself this weekend because it is something that I want the image to support.

**Comment by axi92** [comment]
Any idea why rcon is currently not working? Do I have to do more than set the password in the ini?
I know its currently not possible via the compose or env vars but the server should have rcon enabled if the pw is set in the ini or did I miss something?
I cp the rcon client into the container and used it from there, but it is not working.
```
steam@d276e4b4e13e:~/ZomboidDedicatedServer$ ./rcon -a 127.0.0.1:27015 -p <password> -t rcon
cli: auth: rcon: dial tcp 127.0.0.1:27015: connect: connection refused
```

**Comment by axi92** [comment]
Oh maybe this is blocking it?
https://github.com/Renegade-Master/zomboid-dedicated-server/blob/main/src/run_server.sh#L77

**Comment by Renegade-Master** [comment]
Oh, I see. I should change that regex to be more specific.
I will give that a go, but in the meantime if you want to try it out yourself, you should be able to set the sed command to
```shell
sed -i "s/^Password=.*/Password=$SERVER_PASSWORD/g" "$SERVER_CONFIG"
```

The `^` symbol tells sed to only replace if the line *starts* with "Password", so "RCONPassword" won't be picked up anymore. I will add this to the repo soon though.

**Comment by Renegade-Master** [comment]
So, this might be how you would send a "Shutdown Signal" with RCON. The address thing is because `127.0.0.1` does not work as the listen address.

```bash
docker exec zomboid-dedicated-server bash -c \
      "rcon -a $(cat ZomboidConfig/ip.txt):\${RCON_PORT} -p \${RCON_PASSWORD} quit"
```

In the linked PR, I have made it so that the address that the RCON Server is listening on, is printed to a file in the config directory. The RCON Port and Password can then be picked up as environment variables from within the container.

On the PR is merged, RCON should be working. You will also be able to use an external RCON client to interact with the container.
