### ISSUE TITLE
Folder Permissions on Fedora Linux / Podman

### ISSUE THREAD

**Issue by mvstrawn** [Renegade-Master/zomboid-dedicated-server#19]
**Describe the bug**
I am attempting to build & run this container on Fedora 34 Server Edition, using Podman and Podman-Compose. When the container launches (`podman-compose up --build -d`), these errors are reported:
```
### Setting variables...
/home/steam/run_server.sh: line 187: /home/steam/Zomboid/ip.txt: Permission denied
"### Updating Folder Permissions...
chown: changing ownership of '/home/steam/ZomboidDedicatedServer': Operation not permitted
chown: changing ownership of '/home/steam/Zomboid': Operation not permitted
### Folder Permissions updated.
```
The output of `printf "UID: %s\nGID: %s\n" $(id -u) $(id -g)` on the host:
```
UID: 1000
GID: 1000
```
The folder on the host (/opt/zomboid-dedicated-server):
(strawns is UID/GID 1000)
```
drwxr-xr-x.  8 strawns strawns  4096 Mar 29 18:31 .
drwxr-xr-x. 10 root    root      134 Mar 27 19:31 ..
drwxrwxr-x.  2 strawns strawns    49 Mar 27 19:31 docker
-rw-rw-r--.  1 strawns strawns  2040 Mar 29 18:36 docker-compose.yaml
-rw-rw-r--.  1 strawns strawns    27 Mar 27 19:31 .dockerignore
drwxrwxr-x.  8 strawns strawns   163 Mar 27 19:31 .git
drwxrwxr-x.  4 strawns strawns    45 Mar 27 19:31 .github
-rw-rw-r--.  1 strawns strawns  2616 Mar 27 19:31 .gitignore
-rw-rw-r--.  1 strawns strawns 35413 Mar 27 19:31 LICENSE
-rw-rw-r--.  1 strawns strawns  8057 Mar 27 19:31 README.md
drwxrwxr-x.  2 strawns strawns    83 Mar 27 19:31 src
drwxrwxr-x.  2 strawns strawns     6 Mar 29 18:31 ZomboidConfig
drwxrwxr-x.  2 strawns strawns     6 Mar 29 18:31 ZomboidDedicatedServer
```
I have also edited the docker-compose.yaml file as required by SELinux, which is native to Fedora 34 SE:
```
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer:z
      - ./ZomboidConfig:/home/steam/Zomboid/:z
```
In case the reader is not familiar, the :z appendage informs SELinux to allow other containers to read these volumes, and is necessary for containers to function under F34SE. I have tried :z, :Z (which prevents volume sharing), and setenforce 0 (i.e. turning off SEL file system security); none of these allowed the container's user to modify the folder permissions.
I have also tried commenting out the `user: "1000:1000"` line in the .yaml just in case that was an issue, but the container still reports the steam user as 1000:1000 regardless (and of course my host u/g is still 1000:1000).

Here is the SELinux security context for the files listed above in /opt/zomboid-dedicated-server/:
```
$ ls -Z
       unconfined_u:object_r:usr_t:s0 docker
       unconfined_u:object_r:usr_t:s0 docker-compose.yaml
       unconfined_u:object_r:usr_t:s0 LICENSE
       unconfined_u:object_r:usr_t:s0 README.md
       unconfined_u:object_r:usr_t:s0 src
system_u:object_r:container_file_t:s0 ZomboidConfig
system_u:object_r:container_file_t:s0 ZomboidDedicatedServer
```

So it's understood, the `container_file_t` context is added when the container is started and the .yaml designates those folders as volumes for the container. The folders were created with the `strawns` user, prior to launching the container.

There are other containers running on this system in rootless mode, using the exact same method of creating their volume folders under the non-root user (1000:1000) and they were able to modify the permissions of their respective folders without issue. I'm not sure what is causing the hang-up for this container.

**To Reproduce**
1. Cloned repository.
2. Edited docker-compose.yaml as required
3. `mkdir ZomboidConfig ZomboidDedicatedServer`
4. Built and launched image with `podman-compose up --build -d`

**Expected behavior**
The container should be able to change the permissions for its designated volume folders. It cannot.

**Desktop (please complete the following information):**
 - OS: ```$ uname -a
Linux organization 5.16.17-100.fc34.x86_64 ... SMP PREEMPT Wed Mar 23 15:44:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```
 - Podman Version: ```$ podman --version
podman version 3.4.4```
 - Image Version: `docker.io/renegademaster/steamcmd-minimal          1.0.0       a1b94cb70490  4 months ago  113 MB`

**Additional context**
Just to reiterate, this system is currently running several services in rootless mode with folders for their volumes that had their permissions properly chown'd by Podman/Podman-Compose.

**Comment by Renegade-Master** [comment]
Hello!

Thank you for reporting your issue. And thanks for digging into it so much, answered a lot of the questions I would otherwise have needed to ask.

So the mounted folders (ZomboidConfig and ZomboidDedicatedServer) can be:

1. fully deleted
2. recreated with the correct permissions
3. launch the server

Does the issue persist in this case? The only difference is comfirming that the folders had definitely not been created accidentally by Podman. It does sound like you have eliminatd this possibility already however.

Alternatively, another user was running this in a multi-tennant environment. It was their idea to add the `NO_CHOWN_GAME_DIR` and `NO_CHOWN_CONFIG_DIR` variables in #11. Have you tried using those to prevent the `chown ...` command? If you have handled permissions externally, the `chown` isn't really necessary.

**Comment by mvstrawn** [comment]
>  Does the issue persist in this case?
It does. I deleted and re-created those users as 1000:1000 a couple of times to no avail. Just tried it again to be sure.

> Have you tried using those to prevent the chown ... command?
I added these to my docker-compose.yaml `environment:`
```
      - "NO_CHOWN_GAME_DIR=true"
      - "NO_CHOWN_CONFIG_DIR=true"
```
This is now what I see when the container is built and launched:
```
### Setting variables...
/home/steam/run_server.sh: line 187: /home/steam/Zomboid/ip.txt: Permission denied
"### Updating Folder Permissions...
### Folder Permissions updated.
)### Applying Pre Install Configuration...
&### Pre Install Configuration applied.
&### Updating Project Zomboid Server...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
```
It might be worth noting that some of those lines with the ### are preceded by characters my system isn't displaying so I'm not sure what's there.

Anyway, it is still failing:
```
Success! App '380870' fully installed.
quit

### Project Zomboid Server updated.
(### Checking if this is the first run...
### This is the first run.
Starting server for 60 seconds
&### Starting Project Zomboid Server...
timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory
#### Project Zomboid Server stopped.
### First run check complete.
*### Applying Post Install Configuration...
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
/home/steam/Zomboid/Server/EZombie.ini not found!
sed: can't read /home/steam/ZomboidDedicatedServer/ProjectZomboid64.json: No such file or directory
'### Post Install Configuration applied.
&### Starting Project Zomboid Server...
timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory
#### Project Zomboid Server stopped.
Streaming disconnected

```
I'm assuming that ip.txt file is required and can't be written. I didn't see any mention of it in #11 though.

**Comment by mvstrawn** [comment]
Sorry, I got busy! I am using Nextcloud and its associated services without issue, https://hub.docker.com/_/nextcloud
I think that's what you meant? I'll make sure to check this thread regularly, apologies for the delay.

**Comment by Renegade-Master** [comment]
Thanks for getting back to me about this. I will take a look, and let you know if I come up with anything. 🙂

I'll also let you know if I can't come up with anything, but hopefully that won't happen.

**Comment by Renegade-Master** [comment]
Please comment or reopen if your issue still exists in the most recent version: 2.0.0
