### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by dostoievsky** [Renegade-Master/zomboid-dedicated-server#25]
Hey guys, we are trying set up a server running on linux cloud based ARM architecture. 

when we try to:

```
docker-compose up -d --build

```

we get the following error:

```
[Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 0981c9a412e4
exec /bin/sh: exec format error
The command '/bin/sh -c apt-get update && apt-get autoremove -y     && apt-get install -y --no-install-recommends         python3-minimal     && rm -rf /var/lib/apt/lists/*     && chown -R ${USER_ID}:${GROUP_ID} "/home/steam"' returned a non-zero code: 1
ERROR: Service 'zomboid-server' failed to build : Build failed

```

as we searched on web, is because our system it's not x86_64.

Do you think there is a way to we setup the server at that architecture, or we should abandon that try?

**Comment by Renegade-Master** [comment]
I don't see SteamCMD nor the Zomboid Dedicated Server available for ARM architecture anywhere else at least. I wouldn't necessarily say it can't be done, but it certainly looks like it so far hasn't.

**Comment by Renegade-Master** [comment]
Closing this issue until there is a way to run SteamCMD on ARMv7/64.

**Comment by hangyu-feng** [comment]
@Renegade-Master Can you check out this container [steamcmd-arm64](https://github.com/sonroyaalmerol/steamcmd-arm64) made by @sonroyaalmerol? Is it possible to make it the base image for arm64?

**Comment by Renegade-Master** [comment]
@hangyu-feng I'm not sure it would matter. If Steam ran on ARM64, that is only part of the issue. Zomboid itself also needs to work on ARM64. I don't know personally if it does yet.

**Comment by sonroyaalmerol** [comment]
Hi! I'm the maintainer of the mentioned arm64 base image (thanks for the mention @hangyu-feng).

The base image does include Box64 (an x86_64 emulator for ARM64) which will possibly run Zomboid itself. It has been successful in running Palworld servers (which is probably more complex to emulate) so I'm quite positive about it.

I don't have the game to test but I can help out with the initialization scripts if you're interested.

**Comment by Renegade-Master** [comment]
@sonroyaalmerol 
Thank you for your input!
I'd be interested in giving it a go at some point, sure. How large is the Box64 + dependencies by the way? I'm trying to keep these images light.

I'm also not sure when I will be able to test integration (or even how I would go about it) just yet, but I would be interested to try for sure!
