### ISSUE TITLE
env PUBLIC_SERVER is incorrect or can be misunderstood

### ISSUE THREAD

**Issue by Zhythero** [Renegade-Master/zomboid-dedicated-server#29]
Hi! Thank you for making this convenient image.

Inside `run_server.sh` I would just like to point out that the container's env variable `PUBLIC_SERVER ` is mapped to `Open`
in server settings. However, this is not the case.
The `Open` config does not determine whether the server is publicly listed in server list. It only governs:

> Whether Whitelisting is enabled or not

as per https://pzwiki.net/wiki/Server_Settings

The config that determines whether the server is publicly listed or not is `Public`

**Comment by Renegade-Master** [comment]
Oh, my understanding was what I documented. Sorry about that, you appear to be correct. Luckily that is just a "documentation change". Should be able to fix that without having to release any new versions.

Probably a holdover from a similar config option in another server I made, and I just did not pick up that the purpose of that flag was different for PZ.

**Comment by Renegade-Master** [comment]
Confusingly though, this has always been set to `true` in any Server that I have hosted, and I have never had to add anyone to an "allow-list". Does this perhaps mean something more like:
> Prevent non-allowed Players to see the server in Public Listing

Or do direct IP joins bypass any lists?

You might not know, I just want to get it more accurate this time.
