### ISSUE TITLE
Sleep Allowed and Safehouse Respawn vars not working

### ISSUE THREAD

**Issue by jstirling** [Renegade-Master/zomboid-dedicated-server#3]
The run script uses PLAYER_SAFEHOUSE for both SLEEP_ALLOWED and SAFEHOUSE_RESPAWN, ignoring their values.

https://github.com/Renegade-Master/zomboid-dedicated-server/blob/main/src/run_server.sh#L57
https://github.com/Renegade-Master/zomboid-dedicated-server/blob/main/src/run_server.sh#L60

**Comment by Renegade-Master** [comment]
Ah, my bad.  Bet that was annoying to find.

Should have that fixed next release.
