### ISSUE TITLE
Error with Ubuntu 20.04 ARM64

### ISSUE THREAD

**Issue by FerLuisxd** [Renegade-Master/zomboid-dedicated-server#35]
**Describe the bug**
Cannot run it on ARM64

**To Reproduce**
Followed the exact same guide from the [docker page](https://hub.docker.com/r/renegademaster/zomboid-dedicated-server), I modified the --detach param so I could see the logs. But I get an error , see screenshots 
```
# Pull the latest image:
docker pull renegademaster/zomboid-dedicated-server:latest

# Make two folders
mkdir ZomboidConfig ZomboidDedicatedServer

# Run the server (with bare minimum options):
docker run
    --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer \
    --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
    --publish 16261:16261/udp --publish 8766:8766/udp \
    --name zomboid-server \
    --user=$(id -u):$(id -g) \
    renegademaster/zomboid-dedicated-server:latest
```

**Expected behavior**
The service should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/29811965/184467895-94431e10-4b92-4a41-bfd1-0a89349a4048.png)
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/bash: exec format error
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker Version: 20.10.17
 - Image Version [2.0.0](https://hub.docker.com/layers/zomboid-dedicated-server/renegademaster/zomboid-dedicated-server/2.0.0/images/sha256-c9323655e72ca4f973610998321750e48134e66054aae91db68ca48b0ba67da3?context=explore)

**Additional context**

**Comment by FerLuisxd** [comment]
Ok got a littlbe bit further with 
```
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
```
then adding the --platform param
I'm getting the annoying #8 Error: 
![image](https://user-images.githubusercontent.com/29811965/184474524-5e9dd987-3c89-4924-85bf-bb12d4d44a83.png)
I tried creating a user from 0.
tried creating it with:
```
sudo adduser ferluis
sudo usermod -aG docker ferluis
```
then moving to the user with:
```
sudo su - ferluis
```
Created the folders and ran:
```
docker run --platform linux/amd64 --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer     --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid     --publish 16261:16261/udp --publish 8766:8766/udp     --name zomboid-server     --user=$(id -u):$(id -g)     renegademaster/zomboid-dedicated-server:latest
```
And get the permision denied & file not found error, can you guys help me?

**Comment by FerLuisxd** [comment]
Ok @Renegade-Master got a littlbe bit further with 
```
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
```
then adding the --platform param
I'm getting the annoying #8 Error: 
![image](https://user-images.githubusercontent.com/29811965/184474524-5e9dd987-3c89-4924-85bf-bb12d4d44a83.png)
I tried creating a user from 0.
tried creating it with:
```
sudo adduser ferluis
sudo usermod -aG docker ferluis
```
then moving to the user with:
```
sudo su - ferluis
```
Created the folders and ran:
```
docker run --platform linux/amd64 --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer     --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid     --publish 16261:16261/udp --publish 8766:8766/udp     --name zomboid-server     --user=$(id -u):$(id -g)     renegademaster/zomboid-dedicated-server:latest
```
And get the permision denied & file not found error, can you guys help me?

**Comment by FerLuisxd** [comment]
Just to test, is there a way to "bypass" the root error? Some people don't care that much and it this case I want to test if it could work.

**Comment by Renegade-Master** [comment]
ARM64 isn't supported by SteamCMD.

Can you run SteamCMD without using a Docker container on the same host?

**Comment by FerLuisxd** [comment]
Steamcmd works using docker, so that "problem" is fixed now. I'm having the same issue as #34 and #14. I will try later using docker compose tho! In the meantime can you help me, copy the commands to create a "correct" user, so I can check that too

**Comment by Renegade-Master** [comment]
What image are you running to get SteamCMD working on ARM64?
I was not aware this was possible.

Also I have dropped the User stuff. If you check the README (which I updated ysterday) you can see the revised commands for Docker/Podman and Docker-Compose.

**Comment by FerLuisxd** [comment]
Well it's your image, and saw your image is using debian bullseye, I also tried steam/steamcmd and it works! You just need to add the parameter like I said in the second comment (--platform amd64). I will check the updated guide and update asap!

**Comment by FerLuisxd** [comment]
Tried running it with the readme, but I get the same error 🤔 
![image](https://user-images.githubusercontent.com/29811965/184736137-65ea7c36-e729-4a91-99a5-5cc0206ba1d7.png)
Is there something else I should try?  If we make this to work I'll update the readme as well 👍

**Comment by Renegade-Master** [comment]
That's not quite the same error. The permissions issues appear to be resolved.

Can you try to use `docker-compose` as opposed to `docker compose` as I explain [here]()? They still seem to behave differently even though the documentation says that they are the same now.

Finally, try plain `docker` if possible, please?

If none of those work, I can only assume that the emulation isn't working. Do you not need to configure Buildkit options for platform emulation?

**Comment by FerLuisxd** [comment]
I think I got it? There was a env param needed to get steamcmd running before so I thought of adding it here,
```
      - "CPU_MHZ=2000"
```

This is the new log I'm getting
![image](https://user-images.githubusercontent.com/29811965/184951476-0cb062dd-0bf1-45f6-b715-8c635b4c4f67.png)
It fails after trying to login to the server
```
Connecting anonymously to Steam Public...Bail out! ERROR:../target/i386/tcg/translate.c:8578:i386_tr_init_disas_context: assertion failed: (IOPL(dc) == iopl)
zomboid-dedicated-server    | /usr/bin/steamcmd.sh: line 38:    26 Aborted                 (core dumped) $DEBUGGER "$STEAMEXE" "$@"
```
**This is diffinetly an error with the EMULATION, not permissions.** , I've reported this issue here as well on [their repo](https://github.com/tonistiigi/binfmt/issues/104).
Thanks for the help and hopefully they get it resolved someday

**Comment by Renegade-Master** [comment]
Well that is pretty crazy. Nice one for finding it though, and yeah, hopefully the issue can be resolved!

It'd be nice to be able to use those free server instances for game hosting 🙂

I'm going to close this issue, but pin it to keep it around.

**Comment by FerLuisxd** [comment]
Update regarding this, someone in the community made this possible! (With another docker image that emulates x64)
https://steamcommunity.com/app/108600/discussions/1/3415433168012191380/?ctp=4
