### ISSUE TITLE
Steam update fail, possibly causing clients to not connect?

### ISSUE THREAD

**Issue by xBeEatNUx** [Renegade-Master/zomboid-dedicated-server#41]
**Describe the bug**
Upon pulling the image and running the docker, Steam fails to update. 
This may be causing steam clients to not able to connect even though Steam is enabled.
I have all proper ports open on the docker side and network side and nothing is connected.

**To Reproduce**
1. Pull Image.
2. Start the container with default env vars, 
3. Check the Log and it will show Steam failing to update.

**Expected behavior**
Steam updates the version, fails tries again, fails and reverts to old version

**Desktop (please complete the following information):**
 - OS: Debian Bullseye(Proxmox)
 - Docker Version : 20.10.18

**Additional context**
Just not sure why this container is not passing through the ports correctly. Every other VM is working and port forwarding is working. 
[_zomboid-dedicated-server_logs.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/9758671/_zomboid-dedicated-server_logs.txt)

**Comment by Renegade-Master** [comment]
Try again tomorrow. Tuesday is patch day for Steam.

I'll investigate if it is still present then 👍

**Comment by Renegade-Master** [comment]
Also just to clear some things up:

> I have all proper ports open on the docker side and network side and nothing is connected.

This wouldn't affect Steam being able to update. Open ports allow connections in, but you can still connect to the Internet without them.

> Just not sure why this container is not passing through the ports correctly

We don't know yet if there is any issue with ports. All we know is that Steam cannot connect to the Internet / Steam servers, or Steam pushed a bad Client update.

--- 

The logs indicate that everything is working. I can't see any issue from them.

--- 

What is the output of the command:

```sh
ss -l | grep -E "16261|8766"
```

**Comment by Renegade-Master** [comment]
Finally, I am hoping that it isn't, but it may be related to #42

**Comment by Renegade-Master** [comment]
@xBeEatNUx Is this issue still happening, or was it just a Tuesday thing?

**Comment by xBeEatNUx** [comment]
> 

Not sure I fought with it and decided to go with someone’s else’s build.

**Comment by Renegade-Master** [comment]
No worries. It doesn't seem to have happened to anyone else in the meantime, so I'll close this now.

Glad that you figured something out anyway! 👍

**Comment by xBeEatNUx** [comment]
Not sure if people did what I did or just didn’t report it. Were you not able to try it ?

**Comment by Renegade-Master** [comment]
I tried it. It seems to be fine.

I still have to make the change to add the new UDP port, but that isn't preventing people from joining.
