### ISSUE TITLE
Folders empty, sever running fine - not sure where all the files are to change configuration?

### ISSUE THREAD

**Issue by petruut** [Renegade-Master/zomboid-dedicated-server#44]
Both folders appear empty to me (the ones mapped during the docker deployment). The server is on and reachable by player, so I don't know why the files are not where they should be.

![image](https://user-images.githubusercontent.com/15355480/199275455-66057539-375e-43b6-af2d-501391db7b7f.png)

**Comment by Renegade-Master** [comment]
This looks like an error in your configuration.

`/path/to/folder` is just placeholder text. You need to use a path that actually exists on your Host.

**Comment by petruut** [comment]
Thanks for replying!! I know the naming is terrible, but I do have that actual folder on the HDD... and it's empty.

![image](https://user-images.githubusercontent.com/15355480/199346462-b5dbf550-6feb-4783-b509-56b5be1380d4.png)

**Comment by Renegade-Master** [comment]
The "Path in Container" is also wrong in your screenshot.

You have
`/ZomboidConfig` and `/ZomboidDedicatedServer`

When you should have
`/home/steam/ZomboidConfig` and `/home/steam/ZomboidDedicatedServer`

**Comment by Renegade-Master** [comment]
@petruut is this still an issue?

**Comment by Renegade-Master** [comment]
@petruut 

Please tag me to repoen this issue if the problem is still present.
Thanks for your contribution!
