### ISSUE TITLE
Commands not found when first creating container

### ISSUE THREAD

**Issue by Jmag103** [Renegade-Master/zomboid-dedicated-server#45]
**Describe the bug**
Container starts up and says that I'm missing commands

**To Reproduce**
1. Cloned repository.
2. Made config and server directory
3. Built image with docker-compose file which I did not change
4. Started image using docker-compose up -d
5. See attached error:
Attaching to zomboid-dedicated-server

zomboid-dedicated-server    | /home/steam/run_server.sh: line 2: $'\r': command not found

zomboid-dedicated-server    | /home/steam/run_server.sh: line 20: $'\r': command not found

zomboid-dedicated-server    | /home/steam/run_server.sh: line 27: $'\r': command not found

: invalid option named-server    | /home/steam/run_server.sh: line 29: set: pipefail

zomboid-dedicated-server    | /home/steam/run_server.sh: line 30: $'\r': command not found

zomboid-dedicated-server    | /home/steam/run_server.sh: line 32: syntax error near unexpected token `$'{\r''

'[36mzomboid-dedicated-server    | /home/steam/run_server.sh: line 32: `function shutdown() {

zomboid-dedicated-server exited with code 2

**Expected behavior**
Expected container to be created and server to start

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Docker Version 4.7.0
 - Image Version [e.g. 1.0.0]

**Comment by Jmag103** [comment]
Fixed it. I had to use Notepad ++ to do a EOL Conversion to UNIX

**Comment by Renegade-Master** [comment]
I don't work from Windows, so the line endings should have been LF from the get-go.

Still, glad you figured it out! I'll close this ticket now 👍
