### ISSUE TITLE
[Feature Request] A way to disable "Post Install Configuration"

### ISSUE THREAD

**Issue by Guztaver** [Renegade-Master/zomboid-dedicated-server#52]
I having problems while trying to run after this "Post Install Config", the game stucks on:
```log
zomboid-server              | LOG  : General     , 1668519903797> 41,540,930> LOADING ASSETS: START
```
And before this, the game run normally. So i want to disable this option, but i don't find any way to remove this. I already removed in `run_server.sh`.

**Comment by Renegade-Master** [comment]
Is it "stuck" or is it running out of resources? 

You went out of your way to delete the template that I provide so that I can at least attempt to troubleshoot your issue. I have nothing to go on here.

**Comment by Guztaver** [comment]
Isn't stuck, but i solved after closing/opening several times.
The docker simply get stuck, and you have to restart they, serveral restarts later, the app works.

**Comment by Renegade-Master** [comment]
@Guztaver
Are you running this on a host with limited resources? 

What you described is what I have to do in order to run a server on limited hardware. It takes a few attempts, but it doesn't lose progress and eventually starts.

**Comment by Guztaver** [comment]
> @Guztaver
> Are you running this on a host with limited resources? 
> 
> What you described is what I have to do in order to run a server on limited hardware. It takes a few attempts, but it doesn't lose progress and eventually starts. 

The problem is one, I'm running in ARM64. But i have 20GiB of RAM an 4/4 CPU.

I really don't know how to run in limite resources, but probably making a Arch Linux installation with only the necessary installed, may help you. 
A basic Arch installation consumes around 250MiB of RAM, so have more resources estou run docker

**Comment by Guztaver** [comment]
> > @Guztaver
> > Are you running this on a host with limited resources? 
> > 
> > What you described is what I have to do in order to run a server on limited hardware. It takes a few attempts, but it doesn't lose progress and eventually starts. 
> 
> The problem is one, I'm running in ARM64. But i have 20GiB of RAM an 4/4 CPU.
> 
> I really don't know how to run in limite resources, but probably making a Arch Linux installation with only the necessary installed, may help you. 
> A basic Arch installation consumes around 250MiB of RAM, so have more resources estou run docker

And is worth mentioning, i need estou restart the container several times before they start running. 
Several times they got stuck, and i need to restart until load correctly.
And when appears "LOADING ASSETS: START", i needed wait a lot, before start outputting things.

So basically:
If isn't stuck on "LOADING ASSETS: START", try to restart.

**Comment by Guztaver** [comment]
> > > @Guztaver
> > > Are you running this on a host with limited resources? 
> > > 
> > > What you described is what I have to do in order to run a server on limited hardware. It takes a few attempts, but it doesn't lose progress and eventually starts. 
> > 
> > The problem is one, I'm running in ARM64. But i have 20GiB of RAM an 4/4 CPU.
> > 
> > I really don't know how to run in limite resources, but probably making a Arch Linux installation with only the necessary installed, may help you. 
> > A basic Arch installation consumes around 250MiB of RAM, so have more resources estou run docker
> 
> And is worth mentioning, i need estou restart the container several times before they start running. 
> Several times they got stuck, and i need to restart until load correctly.
> And when appears "LOADING ASSETS: START", i needed wait a lot, before start outputting things.
> 
> So basically:
> If isn't stuck on "LOADING ASSETS: START", try to restart.

And i have small problem with IP, i needed to change in `run.sh` the IP, estou 0.0.0.0, for accept in all the interfaces, so i can connect in the PZ Server.

**Comment by Renegade-Master** [comment]
Zomboid itself doesn't support ARM architecture as far as I know. I'm surprised you managed to get as far as you have.
