### ISSUE TITLE
Bridged Network Issues?

### ISSUE THREAD

**Issue by pogzie** [Renegade-Master/zomboid-dedicated-server#53]
I was able to run your docker image **successfully and connect to my server locally**. I am running the Docker container via my Synology NAS and in my local network everything seems fine.

I have port forwarded 16261 and 16262 (both TCP and UDP) on my Asus router to the same ports to my Synology machine accepting 16261 and 16262 set as both container port and local port (minimizing any port number issues --both TCP and UDP).

I doubled and triple checked the port forwarding are correct. I then turned my attention to if Bridged Network is an issue with this container. Checking the logs, it looks like it jumps off the cliff with an excpetion on `RakNet.Startup()` -- see logs (newest first)

```
2023-01-06T17:01:15.989950112Z	stdout	ERROR: General     , 1673024475989> 8,415,364,347>  at zombie.network.GameServer.main(GameServer.java:739)
2023-01-06T17:01:15.989907450Z	stdout	ERROR: General     , 1673024475989> 8,415,364,347>  at zombie.network.GameServer.startServer(GameServer.java:1454)
2023-01-06T17:01:15.989828633Z	stdout	ERROR: General     , 1673024475989> 8,415,364,347>  at zombie.core.raknet.UdpEngine.<init>(UdpEngine.java:80)
2023-01-06T17:01:15.989618042Z	stdout	ERROR: General     , 1673024475989> 8,415,364,347> java.net.ConnectException: Connection Startup Failed. Code: 5
2023-01-06T17:01:15.989251844Z	stdout	LOG  : Network     , 1673024475988> 8,415,364,346> RakNet.Startup() return code: 5 (0 means success)
2023-01-06T17:01:15.989110965Z	stdout	Unknown bind__() error -1.
2023-01-06T17:01:15.988441611Z	stdout	LOG  : Network     , 1673024475987> 8,415,364,346> [06-01-23 17:01:15.987] > ZNet: Startup version 41.78.16
2023-01-06T17:01:15.988382397Z	stdout	LOG  : Network     , 1673024475987> 8,415,364,345> [06-01-23 17:01:15.987] > ZNet: [-> CZombienet: RakNetPeerInterface_Startup
2023-01-06T17:01:15.988265792Z	stdout	LOG  : Network     , 1673024475987> 8,415,364,345> [06-01-23 17:01:15.987] > ZNet: [-> CZombienet: RakNetPeerInterface_SetOccasionalPing
2023-01-06T17:01:15.987610066Z	stdout	LOG  : Network     , 1673024475986> 8,415,364,344> [06-01-23 17:01:15.986] > ZNet: [-> CZombienet: RakNetPeerInterface_SetIncomingPassword
2023-01-06T17:01:15.614510175Z	stdout	LOG  : Network     , 1673024475577> 8,415,363,935> [06-01-23 17:01:15.577] > ZNet: [-> CZombienet: RakNetPeerInterface_SetServerPort
2023-01-06T17:01:15.614463661Z	stdout	LOG  : Network     , 1673024475577> 8,415,363,935> [06-01-23 17:01:15.577] > ZNet: [-> CZombienet: RakNetPeerInterface_SetServerIP
2023-01-06T17:01:15.614421895Z	stdout	LOG  : Network     , 1673024475577> 8,415,363,935> [06-01-23 17:01:15.576] > ZNet: [-> CZombienet: RakNetPeerInterface_SetMaximumIncomingConnections
2023-01-06T17:01:15.614375435Z	stdout	LOG  : Network     , 1673024475576> 8,415,363,935> [06-01-23 17:01:15.576] > ZNet: [-> CZombienet: RakNetPeerInterface_Init
2023-01-06T17:01:15.614305513Z	stdout	LOG  : Network     , 1673024475576> 8,415,363,934> Initialising RakNet...
```

I dont have any issues using bridge mode with other containers (ie. Nginx works fine) so I dont think its an issue with Synology's Docker daemon. 

Any issues with using this on bridge mode?

**Comment by Renegade-Master** [comment]
Can you please fill out the default [Issue Template](https://github.com/Renegade-Master/zomboid-dedicated-server/issues/new?assignees=&labels=bug&template=bug_report.md&title=)?

It would help if I had the full log, as well as the actual Docker/Podman commands that you might have run.

There should not really be any issues that I can think of involving networking in this image. It does not really do anything involving networking, so it should be hard for that to go wrong.

I did a [quick search](https://www.google.com/search?hl=en&q=project%20zomboid%20%22Unknown%20bind__()%20error%20%2D1%22) and it turned up [this result](https://steamcommunity.com/app/108600/discussions/1/357287304437355362/) which suggests that you may be attempting to bind to a Port that is already in use, or potentially it is an issue with how Project Zomboid binds to an IP. You can't supply 0.0.0.0 to PZ for example and it results in a similar error.

**Comment by pogzie** [comment]
Ok wait, maybe not. I just want to confirm something, in https://github.com/Renegade-Master/zomboid-dedicated-server#docker step 2, you have this: 

```
docker run --detach \
    --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer \
    --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
    --publish 16261:16261/udp --publish 16262:16262/udp [--publish 27015:27015/tcp] \
    --name zomboid-server \
    [--env=ADMIN_PASSWORD=<value>] \
    [--env=ADMIN_USERNAME=<value>] \
    [--env=AUTOSAVE_INTERVAL=<value>] \
    [--env=BIND_IP=<value>] \
    [--env=GAME_PORT=<value>] \
    [--env=GAME_VERSION=<value>] \
    [--env=GC_CONFIG=<value>] \
    [--env=MAP_NAMES=<value>] \
    [--env=MAX_PLAYERS=<value>] \
    [--env=MAX_RAM=<value>] \
    [--env=MOD_NAMES=<value>] \
    [--env=MOD_WORKSHOP_IDS=<value>] \
    [--env=PAUSE_ON_EMPTY=<value>] \
    [--env=PUBLIC_SERVER=<value>] \
    [--env=QUERY_PORT=<value>] \
    [--env=RCON_PASSWORD=<value>] \
    [--env=RCON_PORT=<value>] \
    [--env=SERVER_NAME=<value>] \
    [--env=SERVER_PASSWORD=<value>] \
    [--env=STEAM_VAC=<value>] \
    [--env=USE_STEAM=<value>] \
    docker.io/renegademaster/zomboid-dedicated-server[:<tagname>]
```

But comparing it with the defaults you use for `docker-compose.yaml`  https://github.com/Renegade-Master/zomboid-dedicated-server/blob/d92c1413766450672bb26d60b35628aad0b681fd/docker-compose.yaml#L29-L50 you used `DEFAULT_PORT` and `UDP_PORT`. Which is which? 

Likewise, the `README.md` file says in the chart https://github.com/Renegade-Master/zomboid-dedicated-server#ports `DEFAULT_PORT` and `UDP_PORT` but down a few paragraphs you mention: 

> The strictly required Ports (QUERY_PORT and GAME_PORT) are used by the server to listen for connections and communicate with connected clients. These Ports must be assigned a value, and must be accessible from the Internet (i.e. "forwarded").

Whats the correct env var to use?

**Comment by pogzie** [comment]
**Describe the bug**
Server launches fine (and I can connect and play locally) without specifying `BIND_IP` and ports (gets the local IP of my docker host) but despite port forwarding the needed ports 16261, 16262, (even RCON) 27015, (even the so called UDP_PORT) 8766, external connections to the public IP ends with a "Connection Failed" message in the game.

If I specify my public IP and all the needed ports, server wont launch and crashes and burn with 

```
LOG  : Network     , 1673114812555> 8,505,700,913> Initialising RakNet...
LOG  : Network     , 1673114812556> 8,505,700,915> [07-01-23 18:06:52.556] > ZNet: [-> CZombienet: RakNetPeerInterface_Init
LOG  : Network     , 1673114812557> 8,505,700,915> [07-01-23 18:06:52.557] > ZNet: [-> CZombienet: RakNetPeerInterface_SetMaximumIncomingConnections
LOG  : Network     , 1673114812974> 8,505,701,332> [07-01-23 18:06:52.974] > ZNet: [-> CZombienet: RakNetPeerInterface_SetIncomingPassword
LOG  : Network     , 1673114812975> 8,505,701,333> [07-01-23 18:06:52.975] > ZNet: [-> CZombienet: RakNetPeerInterface_SetOccasionalPing
LOG  : Network     , 1673114812976> 8,505,701,334> [07-01-23 18:06:52.975] > ZNet: [-> CZombienet: RakNetPeerInterface_Startup
LOG  : Network     , 1673114812976> 8,505,701,334> [07-01-23 18:06:52.976] > ZNet: Startup version 41.78.16
Unknown bind__() error -1.
LOG  : Network     , 1673114812998> 8,505,701,356> RakNet.Startup() return code: 5 (0 means success)
ERROR: General     , 1673114812999> 8,505,701,357> java.net.ConnectException: Connection Startup Failed. Code: 5
ERROR: General     , 1673114813000> 8,505,701,358>      at zombie.core.raknet.UdpEngine.<init>(UdpEngine.java:80)
ERROR: General     , 1673114813000> 8,505,701,358>      at zombie.network.GameServer.startServer(GameServer.java:1454)
```
![Screenshot 2023-01-08 000210](https://user-images.githubusercontent.com/1250064/211166097-8a5b0357-04eb-4607-a2ed-35da33e38246.png)
![Screenshot 2023-01-08 024630](https://user-images.githubusercontent.com/1250064/211166100-bfeabbd9-d97d-44f1-9b44-5660ee1f2e0f.png)

**To Reproduce**
Steps to reproduce the behavior:
1. Open Docker in DSM (Synology UI)
2. Go to the Registry tab, search for "Zomboid"
3. Double click renegademaster/zomboid-dedicated-server and choose latest tag (As of 01/08/23)
4. Wait for download to complete
5. Create ZomboidDedicatedServer and ZomboidConfig folders on the docker persistent storage folder
6. Once download is done, go to the Image tab and double click on renegademaster/zomboid-dedicated-server:latest
7. It will prompt the Create Container window
	a. Network: Select "Use the same network as the Docker Host" (this is "host mode")
	b. General Settings: Leave all as default (high privilege, enable resource limitation, enable auto-start -- all unchecked)
	c. General Settings > Advanced: Add all the environment variables (see screenshot) I filled out all the IP/port related configuration under number 2 of https://github.com/Renegade-Master/zomboid-dedicated-server#docker (have to set USE_STEAM to false -- else nasty errors)
	d. Hit Next
	e. Volume Settings > Add Folder > Browse the ZomboidConfig folder > Mount path: /home/steam/Zomboid
	f. Add (another) Folder > Browse the ZomboidDedicatedServer folder > Mount path: /home/steam/ZomboidDedicatedServer
	g. Hit Next > Leave "Run this container after the wizard is finished" > Hit Done
8. Go to the Container tab, double click on the newly created container > watch the Terminal tab (until it dies)


**Expected behavior**
A running Zomboid server which is publicly accessible which does not explode when I put my public IP. 

**Screenshots**
See all attachments (env vars, allowed ports, logs)

**Desktop (please complete the following information):**
 - OS: DSM 7.1-42661 Update 2
 - Docker Version 20.10.3-1308
 - Image Version (latest as of 01/08/23)

**Additional context**
See original post and logs below

[20230108_fresh_install_dockerlogs.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/10367001/20230108_fresh_install_dockerlogs.txt)

[20230108_fresh_install_synologylogs.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/10367000/20230108_fresh_install_synologylogs.txt)

**Comment by Renegade-Master** [comment]
Good catch on the Readme being a bit different to the Docker-Compose configuration. I would say that the Docker-Compose configuration is more likely to be correct, but it needs to be aligned really. This disparity comes from people submitting PRs that cover everything that they are aware of, and me not checking thoroughly enough.

The [run_server.sh:L152](https://github.com/Renegade-Master/zomboid-dedicated-server/blob/main/src/run_server.sh#L152) is the one real "Source of Truth" though. Regardless of what the Readme or Docker-Compose file say, this is where things actually happen.

I am thinking though that you putting you Public IP there doesn't make much sense to me.
Unless your Server is actually a VPS, you probably want to use whatever private IP that the host has, and then pass through the Ports using Port-Forwarding rules. Then Clients would connect using the Public IP that you are assigned by your ISP.

**Comment by pogzie** [comment]
Apparently, it was just a simple issue: 

My port forwarding is 100% correct. Unlike other game servers, it seems PZ would not let you connect to your public IP if you are on the same network. I used my mobile internet to try and connect to my public IP and it worked.

We can close this one now. Maybe we can add that to the readme as well in the section discussing port forwarding.

**Comment by Renegade-Master** [comment]
Yeah, I don't know what The Indie Stone did, but their game is very picky with the IPs that you can provide it with.

Thank you for the help troubleshooting too!
