### ISSUE TITLE
Add rcon-cli

### ISSUE THREAD

**Issue by Foxite** [Renegade-Master/zomboid-dedicated-server#54]
**Is your feature request related to a problem? Please describe.**
Currently rcon can be used using a tool that the user must have installed in their system. This tool could be integrated into the image.

The main benefit of this is that the user will be able to use rcon without needing to expose the container's rcon port, and without needing to install an rcon cli tool. Rcon will be usable by anyone with access to the docker engine. This isn't a security concern, as anyone with access would already be able to read the password through there.

**Describe the solution you'd like**
Install [rcon-cli](https://github.com/itzg/rcon-cli) into the image, as it is used in the wonderful [itzg/minecraft-server](https://github.com/itzg/docker-minecraft-server) image, and use it like so:

    docker-compose exec -it zomboid-server rcon-cli

The tool can be configured to use the password from the environment variables, so no need to specify them each time.

**Additional context**
If you think this is a good idea, I will open a PR to implement this.

**Comment by Renegade-Master** [comment]
RCON is already in the image. It is included from the 'steamcmd-minimal' layer.
Is there something else you are thinking of?

**Comment by Renegade-Master** [comment]
In fact, here is a line in the GitHub Actions where I do pretty much exactly what you suggested while testing:
https://github.com/Renegade-Master/zomboid-dedicated-server/blob/main/.github/workflows/docker-build.yml#L75

**Comment by Foxite** [comment]
Nice. It might be worthwhile to mention this in the documentation.

Jan 9, 2023 10:02:54 PM Renegade-Master ***@***.***>:

**Comment by Renegade-Master** [comment]
Yeah, good point. Next time I get back around to working on this I will try to work it in.

Thanks for the feedback! 🙂
